version: 2.1
executors:
  python:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
commands:
  restore-cache-python:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

  install-dependencies:
    steps:
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  save-cache-python:
    steps:
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  deploy:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "27:dc:ce:a6:75:dd:b0:5a:fd:bd:2b:be:39:73:f8:72"
      - run:
          name: check ssh
          command: |
            ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ansi@54.179.152.172 'cd /home/cicd && ./script.sh'

jobs:
  build:
    executor: python
    steps:
      - checkout
      - restore-cache-python
      - install-dependencies
      - save-cache-python
      - deploy

workflows:
  deploy-or-update-infrastructure:
    jobs:
      - build:
          context: aws
          filters:
            branches:
              only: master